Logging:
    model_directory: '/home/sgarcia/code/CTGANs/models/predictor'
Data_format: 'stage1'
Reco: ['particletype', 'energy', 'direction']
Data:
    # Allow to overwrite config setting based on tasks selection
    allow_overwrite: true
    file_list: '/home/sgarcia/code/CTGANs/balanced.txt'
    mode: 'mono'
    selected_telescope_types: ['LST_LST_LSTCam']
    shuffle: true
    seed: 1234
    image_channels: ['image'] #, 'peak_time']
    mapping_settings:
        camera_types: ['LSTCam']
        mapping_method:
            'LSTCam': 'bilinear_interpolation'
        padding:
            'LSTCam': 2
        mask_interpolation: false
    parameter_selection: 
        - {col_name: "hillas_intensity", min_value: 50.0}
        - {col_name: "leakage_intensity_width_2", max_value: 0.2}
Input:
    shuffle: true
    batch_size_per_worker: 64
    concat_telescopes: false
Model:
    #sudo apt install graphviz
    plot_model: true
    model_directory: '/home/sgarcia/code/ctlearn/ctlearn/default_models/'
    backbone: {module: 'res_net', function: 'res_net_model'}
    head: {module: 'head', function: 'standard_head'}
Model Parameters:
    attention: {mechanism: 'Squeeze-and-Excitation', ratio: 16}
    res_net:
        network: {module: 'resnet_engine', function: 'stacked_res_blocks'}
        #init_layer: {filters: 64, kernel_size: 7, strides: 1}
        #init_max_pool: {size: 3, strides: 2}
        pretrained_weights: null
    single_cnn:
        network: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
    cnn_rnn:
        cnn_block: {module: 'basic', function: 'conv_block'}
        pretrained_weights: null
        dropout_rate: 0.5
    variable_input_model:
        cnn_block: {module: 'basic', function: 'conv_block'}
        telescope_combination: 'feature_maps'
        network_head: {module: 'basic', function: 'conv_head'}
        pretrained_weights: null
    basic:
        conv_block:
            layers:
                - {filters: 32, kernel_size: 3}
                - {filters: 32, kernel_size: 3}
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
            max_pool: {size: 2, strides: 2}
            bottleneck: null
            batchnorm: false
        fully_connect:
            layers: [1024, 512, 256, 128, 64]
            batchnorm: false
        conv_head:
            layers:
                - {filters: 64, kernel_size: 3}
                - {filters: 128, kernel_size: 3}
                - {filters: 256, kernel_size: 3}
            final_avg_pool: true
            batchnorm: false
        batchnorm_decay: 0.99
    resnet_engine:
        name: 'ThinResNet'
        stacked_res_blocks:
            residual_block: 'bottleneck'
            architecture:
                - {filters: 48, blocks: 2}
                - {filters: 96, blocks: 3}
                - {filters: 128, blocks: 3}
                - {filters: 256, blocks: 3}
    standard_head:
        particletype: {class_names: ['proton', 'gamma'], fc_head: [512, 256, 2], weight: 1.0}
        energy: {fc_head: [512, 256, 1], weight: 1.0}
        direction: {fc_head: [512, 256, 2], weight: 1.0}
Training:
    validation_split: 0.05
    num_epochs: 5
    verbose: 2
    workers: 1
    optimizer: 'Adam'
    adam_epsilon: 1.0e-8
    base_learning_rate: 0.0001
    #callbacks:
    #    - {EarlyStopping: {monitor: 'loss', patience: 3, restore_best_weights: True}}
    #scale_learning_rate: false
    #variables_to_train: null

