Data_format: 'dl1dh'
Reco: ['energy', 'direction'] # 'particletype', 
Data:
    file_list: '/home/sgarcia/code/CTGANs/data_files/gamma-diffuse.txt' # TODO: train.txt
    mode: 'mono' # 'stereo'
    selected_telescope_types: ['LST_MAGIC_MAGICCam']
    shuffle: true
    seed: 1234
    image_channels: ['image'] #, 'peak_time']
    mapping_settings:
        camera_types: ['MAGICCam']
        mapping_method:
            'MAGICCam': 'image_shifting'
        padding:
            'MAGICCam': 2
        # interpolation_image_shape:
        #     'LSTCam': [60, 60, 1]
        mask_interpolation: false
    parameter_selection: 
        - {col_name: "hillas_intensity", min_value: 200.0} # 200.0}
        - {col_name: "leakage_intensity_width_2", max_value: 0.1} # 0.0}
Input:
    shuffle: true
    batch_size: 512
Predictor:
    predefined_model_path: 'models/predictor'
    config_path: 'config_files/predictor.yml'
Generator:
    predefined_model_path: false
    latent_dim: 512
    upsampling: true
    layers:
        dense: {units: 4608, use_bias: false, kernel_initializer: orthogonal}
        reshape: {target_shape: [3, 3, 512]}
        upsample_blocks: [
            {filters: 256}, # Upsample to (6, 6, 128)
            {filters: 128}, # Upsample to (12, 12, 64)
            {filters: 64}, # Upsample to (24, 24, 32)
            {filters: 1, use_batchnorm: false} # Upsample to (48, 48, 1)
        ]
        cropping: {cropping: [[2, 3], [2, 3]]} # Crop to (43, 43, 1)
    loss: 
        loss_name: w_gp
        weights: [1, 0.3, 0.3, 0.3]
Discriminator:
    predefined_model_path: false
    layers:
        zeropadding: {padding: [[2, 3], [2, 3]]}
        conv_blocks: [
            {filters: 128, use_batchnorm: false}, # Downsample to (24, 24, 64)
            {filters: 256, use_dropout: true}, # Downsample to (12, 12, 128)
            {filters: 512, use_dropout: true}, # Downsample to (6, 6, 256)
            {filters: 1024} # Downsample to (3, 3, 512)
        ]
    loss: 
        loss_name: w_gp
GANs:
    discriminator_extra_steps: 4
    generator_extra_steps: 1
    gp_weight: 10
    epochs: 100
Callback:
    epochs: 1
    images_dir: images
    models_dir: models