Data_format: 'dl1dh'
Reco: ['particletype', 'energy', 'direction'] # 'particletype', 
Data:
    file_list: 'data_files/gamma-test-lite.txt'
    mode: 'mono' # 'stereo'
    selected_telescope_types: ['LST_MAGIC_MAGICCam']
    shuffle: true
    seed: 1234
    image_channels: ['image'] # , 'peak_time']
    mapping_settings:
        camera_types: ['MAGICCam']
        mapping_method:
            'MAGICCam': 'image_shifting'
        padding:
            'MAGICCam': 2
        # interpolation_image_shape:
        #     'LSTCam': [60, 60, 1]
        mask_interpolation: false
    parameter_selection: 
        - {col_name: "hillas_intensity", min_value: 200.0}
        - {col_name: "leakage_intensity_width_2", max_value: 0.1}
Input:
    shuffle: false
    batch_size: 64

generators_dir: 'models/gamma'
particle_type_classifier: 'models/predictor-particletype'
energy_regressor: 'models/predictor-energy-gamma'
direction_regressor: 'models/predictor-direction-gamma'
total_epochs: 200
epochs_between_models: 1
results_dir: 'test/gamma'